params:
  seed: 42
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: false
    mlp:
      units: [512, 256]
      activation: elu
      initializer:
        name: default
    space:
      continuous:
        mu_activation: tanh
        sigma_activation: softplus
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: false
  config:
    name: mcga_phy_drl
    env_name: mcga_cylinder
    ppo: true
    mixed_precision: true
    torch_compile: false
    normalize_input: true
    normalize_value: false
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    learning_rate: 0.0003
    lr_schedule: adaptive
    kl_threshold: 0.01
    score_to_win: 1000000
    grad_norm: 1.0
    entropy_coef: 0.0
    bounds_loss_coef: 0.0
    truncate_grads: true
    e_clip: 0.2
    clip_value: true
    critic_coef: 2.0
    horizon_length: 32
    minibatch_size: 256
    mini_epochs: 4
    num_actors: 16
    max_epochs: 150
    reward_shaper:
      scale_value: 1.0
    env_config: {}
    features: {}
    train_dir: outputs/rl_runs
